name: CI / CD Workflow
run-name: Build and Deployment started by ${{ github.actor }}
# This workflow will build and deploy the Docker image to the server

on:
  workflow_call:
    inputs:
      docker_user:
        description: 'The Docker username to use to pull the image'
        required: true
        type: string
      image_name:
        description: 'The name of the Docker image to deploy'
        required: true
        type: string
      deployment_user:
        description: 'The user to SSH into the server as'
        required: true
        type: string
      host_port:
        description: 'The port to expose the Docker container on'
        required: true
        type: number
      server_hostname:
        description: 'The hostname of the server to deploy to'
        required: true
        type: string
    
    secrets:
      docker_access_key:
        description: 'Docker Access Key'
        required: true
      server_ssh_key:
        description: 'The SSH key to use to connect to the server'
        required: true
      
jobs:
  build:
    uses: joelyoung01/Templates/.github/workflows/BuildDockerImage.yaml@main
    with:
      docker_username: ${{ github.actor}}
    secrets:
      docker_access_key: ${{ secrets.DOCKER_ACCESS_KEY }}
      
  deploy:
    uses: joelyoung01/Templates/.github/workflows/DeployDockerImage.yaml@main
    needs: build
    with:
      docker_user: ${{ inputs.docker_user }}
      image_name: ${{ inputs.image_name }}
      deployment_user: ${{ inputs.deployment_user }}
      host_port: ${{ inputs.host_port }}
      server_hostname: ${{ inputs.server_hostname }}
    secrets:
      server_ssh_key: ${{ secrets.SERVER_SSH_KEY }}

      
